FolderController/-Service

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -26,11 +26,16 @@ jobs:
         run: mvn checkstyle:check
 
       - name: Run PMD
-        run: mvn pmd:check
+        run: |
+          mvn pmd:check || echo "PMD_FAILED=true" >> $GITHUB_ENV
 
-#      - name: Archive PMD report
-#        if: always()  # dieser Schritt wird immer ausgeführt
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: pmd-report
-#          path: target/pmd.xml
+      - name: Archive PMD report
+        if: env.PMD_FAILED == 'true'
+        uses: actions/upload-artifact@v4
+        with:
+          name: pmd-report
+          path: target/pmd.xml
+
+      - name: Fail if PMD failed
+        if: env.PMD_FAILED == 'true'
+        run: exit 1
